import PDFDocument from 'pdfkit';
import ExcelJS from 'exceljs';
import path from 'path';
import fs from 'fs';
import { Response } from 'express';
import { FloorCheck } from '../models/FloorCheck';
import { FloorCheckLine } from '../models/FloorCheckLine';
import { ApprovalRecord } from '../models/ApprovalRecord';
import { InventoryBalance } from '../models/InventoryBalance';
import { AppError } from '../utils/AppError';
import { format } from 'date-fns';

const reportsDir = path.resolve(__dirname, '../../uploads/reports');
fs.mkdirSync(reportsDir, { recursive: true });

export async function generateFloorCheckPDF(floorCheckId: string, res: Response, organizationId?: string): Promise<void> {
  const filter: Record<string, unknown> = { _id: floorCheckId };
  if (organizationId) filter.organization = organizationId;

  const check = await FloorCheck.findOne(filter)
    .populate('project', 'name')
    .populate('building', 'name')
    .populate('floor', 'name')
    .populate('supervisor', 'fullName');

  if (!check) throw new AppError('Floor check not found', 404);

  const linesFilter: Record<string, unknown> = { floorCheck: floorCheckId };
  if (organizationId) linesFilter.organization = organizationId;

  const lines = await FloorCheckLine.find(linesFilter).populate('item', 'name unit');
  const approvals = await ApprovalRecord.find({
    entityType: 'floor_check',
    entityId: floorCheckId,
    ...(organizationId ? { organization: organizationId } : {}),
  })
    .populate('actor', 'fullName role')
    .sort({ createdAt: 1 });

  const doc = new PDFDocument({ margin: 50, size: 'A4' });
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="floor-check-${floorCheckId}.pdf"`);
  doc.pipe(res);

  // Header
  doc.fontSize(20).font('Helvetica-Bold').text('MIRSAD DAILY OPS', { align: 'center' });
  doc.fontSize(14).font('Helvetica').text('Daily Floor Check Report', { align: 'center' });
  doc.moveDown();
  doc.fontSize(10);

  const proj = check.project as any;
  const bld = check.building as any;
  const flr = check.floor as any;
  const sup = check.supervisor as any;

  doc.text(`Project: ${proj?.name || '-'}   Building: ${bld?.name || '-'}   Floor: ${flr?.name || '-'}`);
  doc.text(`Date: ${format(check.date, 'dd/MM/yyyy')}   Shift: ${check.shift}   Supervisor: ${sup?.fullName || '-'}`);
  doc.text(`Status: ${check.status.toUpperCase()}`);
  doc.moveDown();

  // Lines table
  doc.font('Helvetica-Bold').text('Item Quantities:', { underline: true });
  doc.moveDown(0.5);

  const tableTop = doc.y;
  const colWidths = [180, 70, 70, 70, 80];
  const headers = ['Item', 'Planned', 'Actual', 'Diff', 'Status'];

  let x = 50;
  doc.font('Helvetica-Bold').fontSize(9);
  headers.forEach((h, i) => {
    doc.text(h, x, tableTop, { width: colWidths[i] });
    x += colWidths[i];
  });
  doc.moveTo(50, doc.y + 2).lineTo(545, doc.y + 2).stroke();
  doc.moveDown(0.5);

  doc.font('Helvetica').fontSize(9);
  for (const line of lines) {
    const item = line.item as any;
    const rowY = doc.y;
    x = 50;
    const rowData = [
      `${item?.name || '-'} (${item?.unit || ''})`,
      String(line.plannedQty),
      String(line.actualQty),
      String(line.difference),
      line.lineStatus,
    ];
    rowData.forEach((d, i) => {
      doc.text(d, x, rowY, { width: colWidths[i] });
      x += colWidths[i];
    });
    if (line.notes) {
      doc.fontSize(8).fillColor('grey').text(`  Note: ${line.notes}`, 60);
      doc.fillColor('black').fontSize(9);
    }
  }

  // Approval history
  if (approvals.length > 0) {
    doc.moveDown();
    doc.font('Helvetica-Bold').fontSize(10).text('Approval History:', { underline: true });
    doc.moveDown(0.5);
    doc.font('Helvetica').fontSize(9);
    for (const rec of approvals) {
      const actor = rec.actor as any;
      doc.text(
        `${format(rec.createdAt, 'dd/MM/yyyy HH:mm')}  ${actor?.fullName || '-'} (${rec.step})  →  ${rec.action.toUpperCase()}` +
          (rec.comment ? `\n  Comment: ${rec.comment}` : '')
      );
    }
  }

  doc.moveDown(2);
  doc.fontSize(8).fillColor('grey').text(`Generated by Mirsad Daily Ops — ${format(new Date(), 'dd/MM/yyyy HH:mm')}`, { align: 'center' });
  doc.end();
}

export async function generateFloorCheckExcel(floorCheckId: string, res: Response, organizationId?: string): Promise<void> {
  const filter: Record<string, unknown> = { _id: floorCheckId };
  if (organizationId) filter.organization = organizationId;

  const check = await FloorCheck.findOne(filter)
    .populate('project', 'name')
    .populate('building', 'name')
    .populate('floor', 'name')
    .populate('supervisor', 'fullName');

  if (!check) throw new AppError('Floor check not found', 404);

  const linesFilter: Record<string, unknown> = { floorCheck: floorCheckId };
  if (organizationId) linesFilter.organization = organizationId;

  const lines = await FloorCheckLine.find(linesFilter).populate('item', 'name unit type');

  const workbook = new ExcelJS.Workbook();
  const ws = workbook.addWorksheet('Floor Check');

  ws.columns = [
    { header: 'Item', key: 'item', width: 30 },
    { header: 'Unit', key: 'unit', width: 10 },
    { header: 'Planned Qty', key: 'planned', width: 14 },
    { header: 'Actual Qty', key: 'actual', width: 14 },
    { header: 'Difference', key: 'diff', width: 14 },
    { header: 'Status', key: 'status', width: 18 },
    { header: 'Notes', key: 'notes', width: 30 },
  ];

  ws.getRow(1).font = { bold: true };
  ws.getRow(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF4F46E5' } };
  ws.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } };
  ws.autoFilter = { from: 'A1', to: 'G1' };
  ws.views = [{ state: 'frozen', ySplit: 1 }];

  lines.forEach((line, i) => {
    const item = line.item as any;
    ws.addRow({
      item: item?.name || '-',
      unit: item?.unit || '-',
      planned: line.plannedQty,
      actual: line.actualQty,
      diff: line.difference,
      status: line.lineStatus,
      notes: line.notes || '',
    });
    if (i % 2 === 1) {
      ws.getRow(i + 2).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF5F3FF' } };
    }
  });

  res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
  res.setHeader('Content-Disposition', `attachment; filename="floor-check-${floorCheckId}.xlsx"`);
  await workbook.xlsx.write(res);
}

export async function generateInventoryExcel(
  type: 'food' | 'material',
  period: string,
  res: Response,
  organizationId?: string
): Promise<void> {
  const filter: Record<string, unknown> = { period };
  if (organizationId) filter.organization = organizationId;

  const balances = await InventoryBalance.find(filter)
    .populate({
      path: 'item',
      match: { type },
      populate: { path: 'category', select: 'name' },
    })
    .populate('project', 'name');

  const filtered = balances.filter(b => b.item);

  const workbook = new ExcelJS.Workbook();
  const ws = workbook.addWorksheet(`${type === 'food' ? 'Food' : 'Materials'} Inventory`);

  ws.columns = [
    { header: 'Item', key: 'item', width: 28 },
    { header: 'Category', key: 'category', width: 22 },
    { header: 'Unit', key: 'unit', width: 10 },
    { header: 'Monthly Limit', key: 'limit', width: 15 },
    { header: 'Opening', key: 'opening', width: 12 },
    { header: 'Received', key: 'received', width: 12 },
    { header: 'Consumed', key: 'consumed', width: 12 },
    { header: 'Issued', key: 'issued', width: 12 },
    { header: 'Damaged', key: 'damaged', width: 12 },
    { header: 'Returned', key: 'returned', width: 12 },
    { header: 'Remaining', key: 'remaining', width: 12 },
    { header: 'Status', key: 'status', width: 16 },
  ];

  ws.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } };
  ws.getRow(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF059669' } };
  ws.autoFilter = { from: 'A1', to: 'L1' };
  ws.views = [{ state: 'frozen', ySplit: 1 }];

  filtered.forEach((b, i) => {
    const item = b.item as any;
    ws.addRow({
      item: item?.name || '-',
      category: item?.category?.name || '-',
      unit: item?.unit || '-',
      limit: b.monthlyLimit,
      opening: b.openingBalance,
      received: b.receivedQty,
      consumed: b.consumedQty,
      issued: b.issuedQty,
      damaged: b.damagedQty,
      returned: b.returnedQty,
      remaining: b.remainingQty,
      status: b.status,
    });
    if (i % 2 === 1) {
      ws.getRow(i + 2).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF0FDF4' } };
    }
  });

  res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
  res.setHeader('Content-Disposition', `attachment; filename="${type}-inventory-${period}.xlsx"`);
  await workbook.xlsx.write(res);
}
